version: '3.8'

services:
  universal-mcp-assistant:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
      - LETTA_BASE_URL=http://letta:8283
      - CORS_ORIGINS=*
    volumes:
      - ../config:/app/config:ro
    depends_on:
      - letta
    restart: unless-stopped
    networks:
      - mcp-network

  letta:
    image: letta/letta:latest
    ports:
      - "8283:8283"
    environment:
      - LETTA_SERVER_HOST=0.0.0.0
      - LETTA_SERVER_PORT=8283
    volumes:
      - letta_data:/app/data
    restart: unless-stopped
    networks:
      - mcp-network

volumes:
  letta_data:

networks:
  mcp-network:
    driver: bridge
